# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dem_mosaic_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1420, 617)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_download_dem = QtWidgets.QGroupBox(Form)
        self.groupBox_download_dem.setObjectName("groupBox_download_dem")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_download_dem)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_alos = QtWidgets.QRadioButton(self.groupBox_download_dem)
        self.radioButton_alos.setObjectName("radioButton_alos")
        self.gridLayout_5.addWidget(self.radioButton_alos, 0, 3, 1, 1)
        self.radioButton_srtm = QtWidgets.QRadioButton(self.groupBox_download_dem)
        self.radioButton_srtm.setObjectName("radioButton_srtm")
        self.gridLayout_5.addWidget(self.radioButton_srtm, 0, 2, 1, 1)
        self.spinBox_lon_e = QtWidgets.QSpinBox(self.groupBox_download_dem)
        self.spinBox_lon_e.setMinimumSize(QtCore.QSize(0, 32))
        self.spinBox_lon_e.setAccelerated(True)
        self.spinBox_lon_e.setObjectName("spinBox_lon_e")
        self.gridLayout_5.addWidget(self.spinBox_lon_e, 1, 3, 1, 1)
        self.pushButton_dem_path_d = QtWidgets.QPushButton(self.groupBox_download_dem)
        self.pushButton_dem_path_d.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_dem_path_d.setObjectName("pushButton_dem_path_d")
        self.gridLayout_5.addWidget(self.pushButton_dem_path_d, 3, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_download_dem)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.pushButton_idm_path_d = QtWidgets.QPushButton(self.groupBox_download_dem)
        self.pushButton_idm_path_d.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_idm_path_d.setObjectName("pushButton_idm_path_d")
        self.gridLayout_5.addWidget(self.pushButton_idm_path_d, 5, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_download_dem)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinBox_lat_s = QtWidgets.QSpinBox(self.groupBox_download_dem)
        self.spinBox_lat_s.setMinimumSize(QtCore.QSize(0, 32))
        self.spinBox_lat_s.setAccelerated(True)
        self.spinBox_lat_s.setObjectName("spinBox_lat_s")
        self.gridLayout_5.addWidget(self.spinBox_lat_s, 2, 2, 1, 1)
        self.lineEdit_idm_path = QtWidgets.QLineEdit(self.groupBox_download_dem)
        self.lineEdit_idm_path.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_idm_path.setObjectName("lineEdit_idm_path")
        self.gridLayout_5.addWidget(self.lineEdit_idm_path, 5, 2, 1, 2)
        self.spinBox_lat_n = QtWidgets.QSpinBox(self.groupBox_download_dem)
        self.spinBox_lat_n.setMinimumSize(QtCore.QSize(0, 32))
        self.spinBox_lat_n.setAccelerated(True)
        self.spinBox_lat_n.setObjectName("spinBox_lat_n")
        self.gridLayout_5.addWidget(self.spinBox_lat_n, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_download_dem)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinBox_lon_w = QtWidgets.QSpinBox(self.groupBox_download_dem)
        self.spinBox_lon_w.setMinimumSize(QtCore.QSize(0, 32))
        self.spinBox_lon_w.setAccelerated(True)
        self.spinBox_lon_w.setObjectName("spinBox_lon_w")
        self.gridLayout_5.addWidget(self.spinBox_lon_w, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_download_dem)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 5, 0, 1, 1)
        self.pushButton_get_url = QtWidgets.QPushButton(self.groupBox_download_dem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_get_url.sizePolicy().hasHeightForWidth())
        self.pushButton_get_url.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_get_url.setFont(font)
        self.pushButton_get_url.setObjectName("pushButton_get_url")
        self.gridLayout_5.addWidget(self.pushButton_get_url, 1, 4, 2, 2)
        self.pushButton_add_to_idm = QtWidgets.QPushButton(self.groupBox_download_dem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_to_idm.sizePolicy().hasHeightForWidth())
        self.pushButton_add_to_idm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_add_to_idm.setFont(font)
        self.pushButton_add_to_idm.setObjectName("pushButton_add_to_idm")
        self.gridLayout_5.addWidget(self.pushButton_add_to_idm, 3, 5, 3, 1)
        self.lineEdit_dem_path_d = QtWidgets.QLineEdit(self.groupBox_download_dem)
        self.lineEdit_dem_path_d.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_dem_path_d.setObjectName("lineEdit_dem_path_d")
        self.gridLayout_5.addWidget(self.lineEdit_dem_path_d, 3, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_download_dem)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 1)
        self.gridLayout.addWidget(self.groupBox_download_dem, 0, 0, 1, 2)
        self.groupBox_mosaic_tif = QtWidgets.QGroupBox(Form)
        self.groupBox_mosaic_tif.setObjectName("groupBox_mosaic_tif")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_mosaic_tif)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_tif = QtWidgets.QTextEdit(self.groupBox_mosaic_tif)
        self.textEdit_tif.setObjectName("textEdit_tif")
        self.gridLayout_4.addWidget(self.textEdit_tif, 0, 0, 2, 1)
        self.pushButton_mosaic = QtWidgets.QPushButton(self.groupBox_mosaic_tif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mosaic.sizePolicy().hasHeightForWidth())
        self.pushButton_mosaic.setSizePolicy(sizePolicy)
        self.pushButton_mosaic.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_mosaic.setFont(font)
        self.pushButton_mosaic.setObjectName("pushButton_mosaic")
        self.gridLayout_4.addWidget(self.pushButton_mosaic, 0, 2, 1, 1)
        self.pushButton_plot = QtWidgets.QPushButton(self.groupBox_mosaic_tif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plot.sizePolicy().hasHeightForWidth())
        self.pushButton_plot.setSizePolicy(sizePolicy)
        self.pushButton_plot.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.gridLayout_4.addWidget(self.pushButton_plot, 1, 2, 1, 1)
        self.pushButton_open_tif = QtWidgets.QPushButton(self.groupBox_mosaic_tif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_tif.sizePolicy().hasHeightForWidth())
        self.pushButton_open_tif.setSizePolicy(sizePolicy)
        self.pushButton_open_tif.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_open_tif.setFont(font)
        self.pushButton_open_tif.setObjectName("pushButton_open_tif")
        self.gridLayout_4.addWidget(self.pushButton_open_tif, 0, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_mosaic_tif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_4.addWidget(self.pushButton_clear, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_mosaic_tif, 0, 2, 1, 1)
        self.textEdit_info = TextEdit(Form)
        self.textEdit_info.setMinimumSize(QtCore.QSize(0, 200))
        self.textEdit_info.setReadOnly(True)
        self.textEdit_info.setObjectName("textEdit_info")
        self.gridLayout.addWidget(self.textEdit_info, 5, 0, 1, 3)
        self.groupBox_make_xyz = QtWidgets.QGroupBox(Form)
        self.groupBox_make_xyz.setObjectName("groupBox_make_xyz")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_make_xyz)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_lon_e = QtWidgets.QDoubleSpinBox(self.groupBox_make_xyz)
        self.doubleSpinBox_lon_e.setMinimumSize(QtCore.QSize(0, 32))
        self.doubleSpinBox_lon_e.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_lon_e.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lon_e.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_lon_e.setAccelerated(True)
        self.doubleSpinBox_lon_e.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_lon_e.setPrefix("")
        self.doubleSpinBox_lon_e.setDecimals(1)
        self.doubleSpinBox_lon_e.setMinimum(-180.0)
        self.doubleSpinBox_lon_e.setMaximum(180.0)
        self.doubleSpinBox_lon_e.setSingleStep(0.1)
        self.doubleSpinBox_lon_e.setObjectName("doubleSpinBox_lon_e")
        self.gridLayout_3.addWidget(self.doubleSpinBox_lon_e, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_make_xyz)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_to_xyz = QtWidgets.QPushButton(self.groupBox_make_xyz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_to_xyz.sizePolicy().hasHeightForWidth())
        self.pushButton_to_xyz.setSizePolicy(sizePolicy)
        self.pushButton_to_xyz.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_to_xyz.setFont(font)
        self.pushButton_to_xyz.setObjectName("pushButton_to_xyz")
        self.gridLayout_3.addWidget(self.pushButton_to_xyz, 1, 3, 3, 1)
        self.doubleSpinBox_lat_n = QtWidgets.QDoubleSpinBox(self.groupBox_make_xyz)
        self.doubleSpinBox_lat_n.setMinimumSize(QtCore.QSize(0, 32))
        self.doubleSpinBox_lat_n.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_lat_n.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lat_n.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_lat_n.setAccelerated(True)
        self.doubleSpinBox_lat_n.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_lat_n.setPrefix("")
        self.doubleSpinBox_lat_n.setDecimals(1)
        self.doubleSpinBox_lat_n.setMinimum(-90.0)
        self.doubleSpinBox_lat_n.setMaximum(90.0)
        self.doubleSpinBox_lat_n.setSingleStep(0.1)
        self.doubleSpinBox_lat_n.setObjectName("doubleSpinBox_lat_n")
        self.gridLayout_3.addWidget(self.doubleSpinBox_lat_n, 3, 2, 1, 1)
        self.doubleSpinBox_lat_s = QtWidgets.QDoubleSpinBox(self.groupBox_make_xyz)
        self.doubleSpinBox_lat_s.setMinimumSize(QtCore.QSize(0, 32))
        self.doubleSpinBox_lat_s.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_lat_s.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lat_s.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_lat_s.setAccelerated(True)
        self.doubleSpinBox_lat_s.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_lat_s.setPrefix("")
        self.doubleSpinBox_lat_s.setDecimals(1)
        self.doubleSpinBox_lat_s.setMinimum(-90.0)
        self.doubleSpinBox_lat_s.setMaximum(90.0)
        self.doubleSpinBox_lat_s.setSingleStep(0.1)
        self.doubleSpinBox_lat_s.setObjectName("doubleSpinBox_lat_s")
        self.gridLayout_3.addWidget(self.doubleSpinBox_lat_s, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_make_xyz)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.doubleSpinBox_lon_w = QtWidgets.QDoubleSpinBox(self.groupBox_make_xyz)
        self.doubleSpinBox_lon_w.setMinimumSize(QtCore.QSize(0, 32))
        self.doubleSpinBox_lon_w.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_lon_w.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lon_w.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_lon_w.setAccelerated(True)
        self.doubleSpinBox_lon_w.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_lon_w.setPrefix("")
        self.doubleSpinBox_lon_w.setDecimals(1)
        self.doubleSpinBox_lon_w.setMinimum(-180.0)
        self.doubleSpinBox_lon_w.setMaximum(180.0)
        self.doubleSpinBox_lon_w.setSingleStep(0.1)
        self.doubleSpinBox_lon_w.setObjectName("doubleSpinBox_lon_w")
        self.gridLayout_3.addWidget(self.doubleSpinBox_lon_w, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_make_xyz)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_xyz_path = QtWidgets.QLineEdit(self.groupBox_make_xyz)
        self.lineEdit_xyz_path.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_xyz_path.setObjectName("lineEdit_xyz_path")
        self.gridLayout_3.addWidget(self.lineEdit_xyz_path, 0, 1, 1, 2)
        self.pushButton_xyz_path = QtWidgets.QPushButton(self.groupBox_make_xyz)
        self.pushButton_xyz_path.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_xyz_path.setObjectName("pushButton_xyz_path")
        self.gridLayout_3.addWidget(self.pushButton_xyz_path, 0, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout.addWidget(self.groupBox_make_xyz, 1, 0, 1, 2)
        self.groupBox_make_dem = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_make_dem.sizePolicy().hasHeightForWidth())
        self.groupBox_make_dem.setSizePolicy(sizePolicy)
        self.groupBox_make_dem.setObjectName("groupBox_make_dem")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_make_dem)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_dem_path = QtWidgets.QLineEdit(self.groupBox_make_dem)
        self.lineEdit_dem_path.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_dem_path.setObjectName("lineEdit_dem_path")
        self.gridLayout_2.addWidget(self.lineEdit_dem_path, 1, 2, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox_make_dem)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.radioButton_doris = QtWidgets.QRadioButton(self.groupBox_make_dem)
        self.radioButton_doris.setMinimumSize(QtCore.QSize(0, 32))
        self.radioButton_doris.setObjectName("radioButton_doris")
        self.gridLayout_2.addWidget(self.radioButton_doris, 0, 2, 1, 1)
        self.radioButton_gamma = QtWidgets.QRadioButton(self.groupBox_make_dem)
        self.radioButton_gamma.setMinimumSize(QtCore.QSize(0, 32))
        self.radioButton_gamma.setObjectName("radioButton_gamma")
        self.gridLayout_2.addWidget(self.radioButton_gamma, 0, 3, 1, 1)
        self.radioButton_envi = QtWidgets.QRadioButton(self.groupBox_make_dem)
        self.radioButton_envi.setMinimumSize(QtCore.QSize(0, 32))
        self.radioButton_envi.setCheckable(True)
        self.radioButton_envi.setChecked(False)
        self.radioButton_envi.setObjectName("radioButton_envi")
        self.gridLayout_2.addWidget(self.radioButton_envi, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_make_dem)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.pushButton_make_dem = QtWidgets.QPushButton(self.groupBox_make_dem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_make_dem.sizePolicy().hasHeightForWidth())
        self.pushButton_make_dem.setSizePolicy(sizePolicy)
        self.pushButton_make_dem.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_make_dem.setFont(font)
        self.pushButton_make_dem.setObjectName("pushButton_make_dem")
        self.gridLayout_2.addWidget(self.pushButton_make_dem, 0, 7, 2, 1)
        self.pushButton_dem_path = QtWidgets.QPushButton(self.groupBox_make_dem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dem_path.sizePolicy().hasHeightForWidth())
        self.pushButton_dem_path.setSizePolicy(sizePolicy)
        self.pushButton_dem_path.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_dem_path.setObjectName("pushButton_dem_path")
        self.gridLayout_2.addWidget(self.pushButton_dem_path, 1, 6, 1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout.addWidget(self.groupBox_make_dem, 1, 2, 2, 1)
        self.gridLayout.setRowStretch(5, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Process DEM"))
        self.groupBox_download_dem.setTitle(_translate("Form", "下载SRTM、ALOS DEM"))
        self.radioButton_alos.setText(_translate("Form", "ALOS 30 m (1s)"))
        self.radioButton_srtm.setText(_translate("Form", "SRTM 90 m (3s)"))
        self.spinBox_lon_e.setSuffix(_translate("Form", "°"))
        self.pushButton_dem_path_d.setText(_translate("Form", "选择路径"))
        self.label_8.setText(_translate("Form", "纬度："))
        self.pushButton_idm_path_d.setText(_translate("Form", "选择路径"))
        self.label_6.setText(_translate("Form", "经度："))
        self.spinBox_lat_s.setSuffix(_translate("Form", "°"))
        self.spinBox_lat_n.setSuffix(_translate("Form", "°"))
        self.label_9.setText(_translate("Form", "DEM分辨率："))
        self.spinBox_lon_w.setSuffix(_translate("Form", "°"))
        self.label_11.setText(_translate("Form", "IDMan.exe："))
        self.pushButton_get_url.setText(_translate("Form", "获取DEM下载链接"))
        self.pushButton_add_to_idm.setText(_translate("Form", "添加任务\n"
"到IDM"))
        self.label_10.setText(_translate("Form", "保存路径："))
        self.groupBox_mosaic_tif.setTitle(_translate("Form", "读取、拼接tif文件"))
        self.textEdit_tif.setPlaceholderText(_translate("Form", "点击 \"选择tif\" 按钮以选择tif格式文件"))
        self.pushButton_mosaic.setText(_translate("Form", "读取\n"
"拼接"))
        self.pushButton_plot.setText(_translate("Form", "绘制"))
        self.pushButton_open_tif.setText(_translate("Form", "选择\n"
"tif文件"))
        self.pushButton_clear.setText(_translate("Form", "清空"))
        self.groupBox_make_xyz.setTitle(_translate("Form", "tif2xyz"))
        self.doubleSpinBox_lon_e.setToolTip(_translate("Form", "最大经度"))
        self.doubleSpinBox_lon_e.setSuffix(_translate("Form", "°"))
        self.label_2.setText(_translate("Form", "经度："))
        self.pushButton_to_xyz.setText(_translate("Form", "转为xyz"))
        self.doubleSpinBox_lat_n.setToolTip(_translate("Form", "最大纬度"))
        self.doubleSpinBox_lat_n.setSuffix(_translate("Form", "°"))
        self.doubleSpinBox_lat_s.setToolTip(_translate("Form", "最小纬度"))
        self.doubleSpinBox_lat_s.setSuffix(_translate("Form", "°"))
        self.label_3.setText(_translate("Form", "纬度："))
        self.doubleSpinBox_lon_w.setToolTip(_translate("Form", "最小经度"))
        self.doubleSpinBox_lon_w.setSuffix(_translate("Form", "°"))
        self.label_7.setText(_translate("Form", "保存路径："))
        self.pushButton_xyz_path.setText(_translate("Form", "打开"))
        self.groupBox_make_dem.setTitle(_translate("Form", "tif2dem"))
        self.label_5.setText(_translate("Form", "DEM类型："))
        self.radioButton_doris.setText(_translate("Form", "doris"))
        self.radioButton_gamma.setText(_translate("Form", "gamma"))
        self.radioButton_envi.setText(_translate("Form", "envi"))
        self.label_4.setText(_translate("Form", "保存路径："))
        self.pushButton_make_dem.setText(_translate("Form", "制作DEM"))
        self.pushButton_dem_path.setText(_translate("Form", "打开"))
from textedit import TextEdit
import res_rc
